---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: ophiros
description: Ophiros (codename)
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43
cosign-version: none
nushell-version: none
blue-build-tag: none

modules:
  - type: script
    snippets:
      - sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/_copr_ublue-os-akmods.repo
      - dnf5 config-manager setopt fedora-cisco-openh264.enabled=0

  - type: dnf
    remove:
      packages:
        - ublue-os-udev-rules
        - ublue-os-update-services
        - ublue-os-signing
        - fedora-bookmarks
        - fedora-chromium-config
        - fedora-chromium-config-gnome
        - firefox
        - firefox-langpacks
        - gnome-extensions-app
        - gnome-shell-extension-background-logo
        - gnome-software
        - gnome-software-rpm-ostree
        - gnome-terminal-nautilus
        - podman-docker
        - yelp
        - cosign
        - toolbox

  - type: copy
    from: ghcr.io/ublue-os/brew:latest
    src: /system_files
    dest: /

  - type: copy
    from: ghcr.io/projectbluefin/common:latest
    src: /system_files/shared/usr/lib/udev
    dest: /usr/lib/udev

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - swap-kernel.sh

  - type: script
    snippets:
      - rm -rf /usr/src
      - rm -rf /usr/share/doc
      - rm -rf /usr/share/man
      - rpm --erase --nodeps kernel-cachyos-devel    
      - dnf5 clean all
      - flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - type: systemd
    system:
      enabled:
        - systemd-timesyncd.service
        - systemd-resolved.service
        - brew-setup.service
      disabled:
        - rpm-ostree-countme.service
        - rpm-ostreed-automatic.timer
      masked:
        - flatpak-add-fedora-repos.service

  - type: initramfs

  - type: signing
